In [1]:
import pandas as pd

In [2]:
# 1
df = pd.read_csv("/content/students - students.csv")

In [3]:
# 2
df.head(5)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,0.2,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5,78.7,48.4,54.0,...,3.6,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes
2,DS003,Aditya Gupta,Female,20.0,7,75.3,1.1,96.8,73.8,60.1,...,1.8,101,3,Beginner,Medium,35.7,69.1,C,Low,Video Tutorials and Quizzes
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,6.2,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6,66.4,56.3,88.9,...,2.2,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes

In [4]:
# 3
df.tail(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.4,...,7.5,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,7.7,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects
192,DS193,Saurabh Mishra,Male,22.0,7,94.4,1.9,60.3,47.8,78.9,...,2.2,93,2,Intermediate,High,46.2,78.0,B,Low,Practice Exercises
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,1.5,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,5.9,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.9,...,3.5,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

In [52]:
# 4
df.shape

(200, 22)

In [51]:
# 5
df.columns

Index(['student_id', 'student_name', 'gender', 'age', 'semester',
       'attendance_percent', 'study_hours_per_day', 'assignment_average',
       'quiz_average', 'mid_sem_score', 'previous_cgpa', 'lab_hours_per_week',
       'online_activity_count', 'projects_completed', 'python_skill_level',
       'mathematics_skill', 'engagement_score', 'predicted_score', 'grade',
       'risk_level', 'learning_recommendation', 'rank'],
      dtype='object')

In [50]:
# 6
df.dtypes

student_id                  object
student_name                object
gender                      object
age                        float64
semester                     int64
attendance_percent         float64
study_hours_per_day        float64
assignment_average         float64
quiz_average               float64
mid_sem_score              float64
previous_cgpa              float64
lab_hours_per_week         float64
online_activity_count        int64
projects_completed           int64
python_skill_level          object
mathematics_skill           object
engagement_score           float64
predicted_score            float64
grade                       object
risk_level                  object
learning_recommendation     object
rank                       float64
dtype: object

In [49]:
# 7
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               200 non-null    object
 1   student_name             200 non-null    object
 2   gender                   200 non-null    object
 3   age                      198 non-null    float64
 4   semester                 200 non-null    int64
 5   attendance_percent       200 non-null    float64
 6   study_hours_per_day      200 non-null    float64
 7   assignment_average       196 non-null    float64
 8   quiz_average             200 non-null    float64
 9   mid_sem_score            200 non-null    float64
 10  previous_cgpa            200 non-null    float64
 11  lab_hours_per_week       199 non-null    float64
 12  online_activity_count    200 non-null    int64
 13  projects_completed       200 non-null    int64
 14  python_skill_level       200 non-null    object
 15  mathematics_skill        191 non-null    object
 16  engagement_score         200 non-null    float64
 17  predicted_score          200 non-null    float64
 18  grade                    200 non-null    object
 19  risk_level               200 non-null    object
 20  learning_recommendation  200 non-null    object
 21  rank                     200 non-null    float64
dtypes: float64(11), int64(3), object(8)
memory usage: 34.5+ KB

In [48]:
# 8
df.describe()

,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,previous_cgpa,lab_hours_per_week,online_activity_count,projects_completed,engagement_score,predicted_score,rank
count,198.000000,200.000000,200.000000,200.000000,196.000000,200.000000,200.000000,200.000000,199.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,20.590909,5.580000,77.457500,3.428500,72.382143,69.936500,66.056500,7.370100,3.973367,108.105000,2.330000,55.441500,77.891000,100.500000
std,1.744991,1.657509,12.294528,1.473156,16.642918,17.479347,18.575319,1.442061,2.184413,54.821446,1.656751,12.934494,7.911789,57.877144
min,18.000000,3.000000,55.000000,1.000000,45.300000,40.300000,35.000000,5.040000,0.000000,10.000000,0.000000,26.700000,60.000000,1.000000
25%,19.000000,4.000000,67.150000,2.200000,57.175000,54.050000,50.775000,6.135000,2.200000,58.000000,1.000000,46.350000,71.675000,50.750000
50%,21.000000,6.000000,77.950000,3.400000,71.400000,70.100000,65.050000,7.310000,3.800000,110.000000,2.000000,54.900000,78.150000,100.250000
75%,22.000000,7.000000,88.500000,4.600000,88.925000,84.925000,82.525000,8.655000,5.700000,156.000000,4.000000,66.425000,83.825000,150.375000
max,23.000000,8.000000,99.800000,6.000000,99.800000,99.900000,99.500000,9.800000,8.000000,200.000000,5.000000,83.800000,96.300000,200.000000

In [47]:
# 9
df.isnull().sum()

student_id                 0
student_name               0
gender                     0
age                        2
semester                   0
attendance_percent         0
study_hours_per_day        0
assignment_average         4
quiz_average               0
mid_sem_score              0
previous_cgpa              0
lab_hours_per_week         1
online_activity_count      0
projects_completed         0
python_skill_level         0
mathematics_skill          9
engagement_score           0
predicted_score            0
grade                      0
risk_level                 0
learning_recommendation    0
rank                       0
dtype: int64

In [46]:
# 10
df.nunique()

student_id                 200
student_name               123
gender                       2
age                          6
semester                     6
attendance_percent         166
study_hours_per_day         51
assignment_average         160
quiz_average               171
mid_sem_score              171
previous_cgpa              165
lab_hours_per_week          75
online_activity_count      130
projects_completed           6
python_skill_level           3
mathematics_skill            3
engagement_score           170
predicted_score            146
grade                        4
risk_level                   3
learning_recommendation      4
rank                       146
dtype: int64

In [45]:
# 11
df[["student_name", "gender", "semester"]]

      student_name  gender  semester
0     Nisha Pandey    Male         7
1    Aarav Chauhan  Female         7
2     Aditya Gupta  Female         7
3     Aditya Kumar    Male         4
4      Neha Pandey  Female         6
..             ...     ...       ...
195    Aarav Verma  Female         6
196  Arjun Chauhan    Male         3
197     Neha Kumar  Female         4
198    Priya Gupta    Male         7
199   Vivaan Singh    Male         7

[200 rows x 3 columns]

In [44]:
# 12
df[df["semester"] == 3]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
17,DS018,Arjun Sharma,Male,18.0,3,99.8,3.3,60.4,93.0,83.6,...,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects,8.0
18,DS019,Aarav Sharma,Female,NaN,3,72.8,5.2,96.2,44.2,48.6,...,136,2,Beginner,Medium,70.7,80.9,B,Medium,Practice Exercises,70.0
31,DS032,Ananya Singh,Male,21.0,3,89.3,4.1,50.6,45.0,80.6,...,131,1,Beginner,Low,65.6,70.0,C,Low,Video Tutorials and Quizzes,167.5
38,DS039,Riya Kumar,Female,19.0,3,73.7,2.4,NaN,91.9,87.8,...,190,4,Intermediate,High,52.8,84.7,B,Medium,Practice Exercises,45.0
39,DS040,Riya Gupta,Male,23.0,3,60.8,5.8,78.3,53.7,78.7,...,81,1,Intermediate,Medium,68.1,84.2,B,High,Practice Exercises,47.0
44,DS045,Rahul Kumar,Male,22.0,3,71.0,5.5,52.1,59.8,55.9,...,65,5,Beginner,Medium,67.0,70.0,C,Medium,Video Tutorials and Quizzes,167.5
60,DS061,Kunal Chauhan,Male,21.0,3,55.2,2.7,66.9,72.2,94.8,...,171,2,Intermediate,Medium,49.1,75.6,B,High,Practice Exercises,120.0
64,DS065,Simran Mishra,Male,22.0,3,79.8,2.3,NaN,70.3,73.7,...,60,0,Intermediate,Medium,43.1,71.6,C,Low,Video Tutorials and Quizzes,151.5
77,DS078,Riya Gupta,Male,21.0,3,81.1,2.4,66.9,45.5,56.9,...,186,2,Intermediate,Medium,54.4,68.9,C,Low,Video Tutorials and Quizzes,176.0
94,DS095,Aryan Singh,Female,21.0,3,78.3,1.4,64.3,42.0,40.1,...,112,1,Intermediate,High,39.7,60.0,D,Medium,Extra Mentoring and Practice,200.0
95,DS096,Saurabh Mishra,Female,21.0,3,97.8,1.6,94.3,75.7,75.1,...,17,1,Intermediate,High,38.6,83.9,B,Low,Practice Exercises,50.0
101,DS102,Aditya Gupta,Female,22.0,3,89.8,1.7,98.3,67.2,50.3,...,102,1,Intermediate,Low,44.2,70.7,C,Low,Video Tutorials and Quizzes,155.5
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.8,...,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises,103.0
115,DS116,Vivaan Kumar,Female,22.0,3,63.0,2.6,57.7,52.4,76.5,...,194,5,Beginner,Medium,52.1,66.6,C,High,Video Tutorials and Quizzes,184.0
117,DS118,Arjun Sharma,Male,18.0,3,65.2,2.8,48.8,71.1,39.4,...,158,5,Intermediate,Medium,51.3,69.6,C,Medium,Video Tutorials and Quizzes,172.0
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects,17.0
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.6,...,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects,29.5
138,DS139,Saurabh Singh,Female,20.0,3,80.0,4.7,78.9,51.3,58.1,...,95,1,Intermediate,Low,65.2,81.9,B,Low,Practice Exercises,61.5
142,DS143,Isha Verma,Female,23.0,3,74.5,1.4,57.1,75.9,82.8,...,54,0,Intermediate,Medium,34.1,79.9,B,Medium,Practice Exercises,83.5
145,DS146,Aman Singh,Male,20.0,3,90.1,1.0,48.2,53.5,43.5,...,45,4,Beginner,Low,34.1,60.3,D,Medium,Extra Mentoring and Practice,199.0
149,DS150,Saurabh Sinha,Male,23.0,3,78.6,1.6,92.3,83.4,39.4,...,107,0,Intermediate,Low,41.0,77.1,B,Low,Practice Exercises,110.0
159,DS160,Aditya Verma,Female,19.0,3,64.7,2.8,48.8,85.8,61.5,...,154,0,Intermediate,Medium,50.9,75.7,B,High,Practice Exercises,118.0
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.5,...,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects,38.5
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises,114.5
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises,99.5
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects,29.5

In [43]:
# 13
df[df["gender"] == "Female"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5,78.7,48.4,54.0,...,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes,177.0
2,DS003,Aditya Gupta,Female,20.0,7,75.3,1.1,96.8,73.8,60.1,...,101,3,Beginner,Medium,35.7,69.1,C,Low,Video Tutorials and Quizzes,175.0
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6,66.4,56.3,88.9,...,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes,151.5
6,DS007,Aarav Mishra,Female,23.0,7,87.8,4.2,93.8,68.3,42.8,...,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises,54.0
7,DS008,Sneha Sharma,Female,18.0,6,80.3,4.5,52.7,76.3,70.1,...,80,2,Intermediate,High,62.5,75.7,B,Low,Practice Exercises,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects,14.5
187,DS188,Vivaan Chauhan,Female,22.0,6,93.9,3.0,61.1,49.1,52.3,...,48,0,Intermediate,Medium,51.3,64.5,D,Medium,Extra Mentoring and Practice,193.0
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.5,...,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes,163.0
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.9,...,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes,161.5

In [42]:
# 14
df[df["previous_cgpa"] > 8.0]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises,125.0
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises,81.0
6,DS007,Aarav Mishra,Female,23.0,7,87.8,4.2,93.8,68.3,42.8,...,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises,54.0
9,DS010,Nisha Sinha,Male,20.0,8,78.0,3.1,57.2,47.2,56.9,...,105,0,Intermediate,Low,52.7,74.4,C,Low,Video Tutorials and Quizzes,133.0
12,DS013,Aditya Verma,Female,21.0,5,64.9,4.6,89.5,60.9,41.3,...,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,DS193,Saurabh Mishra,Male,22.0,7,94.4,1.9,60.3,47.8,78.9,...,93,2,Intermediate,High,46.2,78.0,B,Low,Practice Exercises,103.0
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises,114.5
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects,29.5
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects,16.0

In [41]:
# 15
df[df["attendance_percent"] < 75]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises,125.0
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5,78.7,48.4,54.0,...,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes,177.0
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6,66.4,56.3,88.9,...,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes,151.5
5,DS006,Aman Sinha,Male,18.0,6,68.2,1.1,55.9,82.7,86.4,...,50,3,Advanced,Medium,29.9,74.8,C,Medium,Video Tutorials and Quizzes,128.0
10,DS011,Nisha Mishra,Female,19.0,5,68.5,2.4,47.0,76.6,67.7,...,138,2,Intermediate,Medium,47.4,65.0,C,Medium,Video Tutorials and Quizzes,192.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,DS183,Isha Gupta,Male,23.0,5,73.3,5.1,87.0,74.4,97.1,...,125,4,Intermediate,High,69.1,87.2,A,Medium,Advanced Projects,25.0
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects,14.5
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.5,...,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes,163.0
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects,23.0
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5

In [40]:
# 16
df[df["study_hours_per_day"] > 4]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
6,DS007,Aarav Mishra,Female,23.0,7,87.8,4.2,93.8,68.3,42.8,...,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises,54.0
7,DS008,Sneha Sharma,Female,18.0,6,80.3,4.5,52.7,76.3,70.1,...,80,2,Intermediate,High,62.5,75.7,B,Low,Practice Exercises,118.0
12,DS013,Aditya Verma,Female,21.0,5,64.9,4.6,89.5,60.9,41.3,...,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises,59.0
13,DS014,Simran Mishra,Male,23.0,4,66.6,4.3,89.9,73.3,69.4,...,149,4,Advanced,Medium,63.0,79.9,B,Medium,Practice Exercises,83.5
15,DS016,Kavya Singh,Female,19.0,8,75.2,6.0,54.7,41.1,67.1,...,145,2,Intermediate,Medium,78.4,72.2,C,Low,Video Tutorials and Quizzes,147.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.5,...,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes,163.0
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects,23.0
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises,99.5
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0

In [39]:
# 17
df[df["python_skill_level"] == "Advanced"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises,125.0
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises,81.0
5,DS006,Aman Sinha,Male,18.0,6,68.2,1.1,55.9,82.7,86.4,...,50,3,Advanced,Medium,29.9,74.8,C,Medium,Video Tutorials and Quizzes,128.0
12,DS013,Aditya Verma,Female,21.0,5,64.9,4.6,89.5,60.9,41.3,...,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises,59.0
13,DS014,Simran Mishra,Male,23.0,4,66.6,4.3,89.9,73.3,69.4,...,149,4,Advanced,Medium,63.0,79.9,B,Medium,Practice Exercises,83.5
14,DS015,Kunal Sharma,Male,20.0,5,93.5,3.0,93.8,91.1,95.8,...,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects,2.0
25,DS026,Nisha Chauhan,Female,19.0,5,77.6,5.3,81.2,49.8,39.6,...,137,2,Advanced,Medium,72.8,78.1,B,Low,Practice Exercises,101.0
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,2.8,59.3,67.2,37.1,...,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice,194.0
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,3.8,50.0,83.6,70.6,...,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises,96.5
46,DS047,Aditya Mishra,Male,23.0,5,78.9,1.5,69.6,72.0,50.8,...,48,0,Advanced,Low,35.6,67.0,C,Low,Video Tutorials and Quizzes,183.0
48,DS049,Rahul Verma,Male,19.0,4,66.0,3.5,63.2,96.0,35.5,...,121,3,Advanced,Low,54.2,70.5,C,Medium,Video Tutorials and Quizzes,161.5
63,DS064,Simran Singh,Male,23.0,6,76.6,3.5,87.1,46.2,56.7,...,19,1,Advanced,Medium,48.7,69.2,C,Low,Video Tutorials and Quizzes,173.5
66,DS067,Simran Singh,Female,18.0,7,70.4,2.3,65.9,75.4,52.4,...,146,1,Advanced,Medium,47.7,72.9,C,Medium,Video Tutorials and Quizzes,142.0
69,DS070,Rahul Pandey,Male,19.0,6,83.5,3.5,76.5,90.3,61.3,...,139,3,Advanced,Low,60.0,86.1,A,Low,Advanced Projects,36.0
81,DS082,Aditya Yadav,Male,22.0,7,79.2,4.0,76.9,45.5,92.0,...,146,2,Advanced,High,63.5,77.8,B,Low,Practice Exercises,105.0
83,DS084,Riya Singh,Male,22.0,8,81.7,5.1,64.1,80.7,71.8,...,156,3,Advanced,High,73.7,81.6,B,Low,Practice Exercises,65.5
84,DS085,Sneha Sinha,Male,22.0,4,59.8,4.5,55.4,92.9,97.5,...,179,1,Advanced,Medium,65.3,84.8,B,High,Practice Exercises,44.0
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.9,...,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects,12.0
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects,22.0
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.8,...,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises,103.0
111,DS112,Neha Sinha,Female,21.0,5,72.1,2.0,71.4,51.7,45.8,...,36,4,Advanced,Medium,36.9,67.7,C,Medium,Video Tutorials and Quizzes,179.0
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects,17.0
128,DS129,Rohan Kumar,Male,22.0,7,92.5,4.1,55.9,43.9,37.8,...,148,4,Advanced,Low,67.8,67.3,C,Low,Video Tutorials and Quizzes,180.5
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects,5.0
131,DS132,Priya Kumar,Male,22.0,7,56.7,4.7,81.2,88.1,41.8,...,67,5,Advanced,High,57.1,73.0,C,High,Video Tutorials and Quizzes,140.5
132,DS133,Aman Sharma,Male,21.0,5,62.8,1.5,81.3,85.9,52.2,...,90,0,Advanced,Medium,34.9,66.5,C,High,Video Tutorials and Quizzes,185.5
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.8,...,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises,69.0
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.6,...,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects,29.5
137,DS138,Isha Mishra,Female,22.0,8,94.3,4.2,86.9,49.6,65.0,...,14,2,Advanced,Low,58.3,74.7,C,Low,Video Tutorials and Quizzes,129.5
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.4,...,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes,153.0
143,DS144,Neha Yadav,Female,23.0,6,72.3,3.9,77.3,51.1,58.5,...,122,5,Advanced,Medium,59.0,72.5,C,Medium,Video Tutorials and Quizzes,144.5
156,DS157,Nisha Singh,Male,19.0,8,72.1,5.9,63.5,57.8,94.7,...,130,2,Advanced,Medium,75.6,80.3,B,Medium,Practice Exercises,78.0
158,DS159,Pooja Yadav,Male,18.0,7,91.3,5.2,59.0,41.9,83.1,...,165,5,Advanced,Medium,77.6,75.1,B,Low,Practice Exercises,127.0
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.7,...,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice,195.0
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.0,...,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects,7.0
181,DS182,Isha Chauhan,Male,21.0,6,89.0,3.5,61.6,69.5,69.0,...,164,2,Advanced,Medium,63.4,79.1,B,Low,Practice Exercises,90.5
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.4,...,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises,54.0
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises,114.5
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects,16.0

In [38]:
# 18
df[df["grade"] == "A"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
14,DS015,Kunal Sharma,Male,20.0,5,93.5,3.0,93.8,91.1,95.8,...,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects,2.0
16,DS017,Isha Yadav,Female,23.0,8,81.5,5.9,71.8,94.4,63.2,...,120,0,Beginner,Medium,77.2,87.1,A,Low,Advanced Projects,26.5
17,DS018,Arjun Sharma,Male,18.0,3,99.8,3.3,60.4,93.0,83.6,...,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects,8.0
19,DS020,Aarav Sinha,Female,20.0,8,71.2,2.5,89.5,88.6,91.4,...,66,3,Intermediate,Medium,43.1,91.1,A,Medium,Advanced Projects,9.5
28,DS029,Saurabh Gupta,Female,18.0,5,99.6,3.1,65.5,86.6,57.2,...,122,4,Intermediate,Medium,59.5,85.9,A,Low,Advanced Projects,37.0
35,DS036,Neha Kumar,Female,22.0,8,81.3,5.5,47.5,56.9,96.8,...,165,4,Beginner,Low,77.5,88.0,A,Low,Advanced Projects,20.0
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects,4.0
52,DS053,Ananya Pandey,Male,23.0,5,70.7,5.6,90.7,97.9,43.1,...,85,2,Beginner,Medium,69.3,90.2,A,Medium,Advanced Projects,13.0
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.2,...,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects,38.5
55,DS056,Aman Sharma,Male,19.0,6,90.7,4.1,74.3,93.6,86.3,...,164,0,Beginner,Medium,68.6,85.4,A,Low,Advanced Projects,40.0
69,DS070,Rahul Pandey,Male,19.0,6,83.5,3.5,76.5,90.3,61.3,...,139,3,Advanced,Low,60.0,86.1,A,Low,Advanced Projects,36.0
71,DS072,Arjun Verma,Female,20.0,5,92.9,5.2,97.5,49.3,75.5,...,49,0,Intermediate,Medium,68.7,87.1,A,Low,Advanced Projects,26.5
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects,1.0
87,DS088,Saurabh Yadav,Male,18.0,8,82.9,1.2,92.9,98.4,98.0,...,134,3,Beginner,Low,41.0,90.6,A,Low,Advanced Projects,11.0
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.8,...,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects,34.5
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.9,...,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects,12.0
104,DS105,Nisha Gupta,Female,19.0,5,55.2,5.8,80.2,92.1,64.6,...,181,5,Beginner,Low,74.7,86.8,A,High,Advanced Projects,29.5
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects,22.0
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects,33.0
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.0,...,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects,19.0
114,DS115,Saurabh Pandey,Female,18.0,4,66.5,2.5,85.3,91.1,78.6,...,192,1,Beginner,Medium,52.0,86.5,A,Medium,Advanced Projects,32.0
119,DS120,Pooja Chauhan,Male,23.0,8,75.3,4.8,64.1,79.9,86.7,...,101,2,Beginner,High,65.3,91.1,A,Low,Advanced Projects,9.5
121,DS122,Kunal Gupta,Female,19.0,5,65.8,3.5,90.4,56.8,96.3,...,159,2,Intermediate,Medium,57.2,87.9,A,Medium,Advanced Projects,21.0
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.4,...,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects,3.0
123,DS124,Simran Verma,Male,19.0,4,92.0,1.7,92.4,95.4,66.7,...,134,3,Intermediate,Medium,47.3,85.0,A,Low,Advanced Projects,41.0
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects,17.0
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects,5.0
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.0,...,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects,29.5
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.6,...,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects,29.5
147,DS148,Arjun Singh,Male,18.0,5,70.6,5.5,46.2,79.8,97.6,...,179,1,Intermediate,Medium,76.0,86.3,A,Medium,Advanced Projects,34.5
151,DS152,Aman Gupta,Female,21.0,4,69.9,4.8,73.6,52.3,92.1,...,164,4,Intermediate,High,69.0,87.4,A,Medium,Advanced Projects,24.0
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.7,...,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects,14.5
169,DS170,Sneha Kumar,Male,21.0,5,73.5,5.5,84.3,76.5,55.1,...,17,0,Intermediate,Low,63.7,88.7,A,Medium,Advanced Projects,18.0
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.0,...,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects,7.0
182,DS183,Isha Gupta,Male,23.0,5,73.3,5.1,87.0,74.4,97.1,...,125,4,Intermediate,High,69.1,87.2,A,Medium,Advanced Projects,25.0
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects,14.5
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.5,...,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects,38.5
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects,23.0
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects,29.5
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects,16.0

In [37]:
# 19
df[df["risk_level"] == "High"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises,125.0
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6,66.4,56.3,88.9,...,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes,151.5
12,DS013,Aditya Verma,Female,21.0,5,64.9,4.6,89.5,60.9,41.3,...,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises,59.0
20,DS021,Kavya Sharma,Female,21.0,4,59.2,3.9,47.0,67.9,70.3,...,95,0,Beginner,High,53.6,69.8,C,High,Video Tutorials and Quizzes,170.0
33,DS034,Aditya Singh,Female,21.0,8,57.5,1.6,51.5,79.0,83.5,...,200,3,Beginner,High,43.2,72.4,C,High,Video Tutorials and Quizzes,146.0
37,DS038,Isha Gupta,Female,18.0,4,58.7,5.4,75.3,49.9,61.7,...,186,2,Intermediate,Medium,72.8,80.5,B,High,Practice Exercises,74.5
39,DS040,Riya Gupta,Male,23.0,3,60.8,5.8,78.3,53.7,78.7,...,81,1,Intermediate,Medium,68.1,84.2,B,High,Practice Exercises,47.0
45,DS046,Arjun Kumar,Male,18.0,5,63.3,2.0,65.4,69.1,75.2,...,118,1,Beginner,Medium,41.3,70.7,C,High,Video Tutorials and Quizzes,155.5
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects,4.0
60,DS061,Kunal Chauhan,Male,21.0,3,55.2,2.7,66.9,72.2,94.8,...,171,2,Intermediate,Medium,49.1,75.6,B,High,Practice Exercises,120.0
72,DS073,Saurabh Sinha,Female,20.0,5,58.5,1.0,98.2,40.3,41.7,...,58,4,Intermediate,Medium,27.3,61.2,D,High,Extra Mentoring and Practice,196.0
78,DS079,Arjun Singh,Female,23.0,7,56.9,1.1,99.3,65.7,60.0,...,46,4,Beginner,Medium,26.7,74.2,C,High,Video Tutorials and Quizzes,134.5
84,DS085,Sneha Sinha,Male,22.0,4,59.8,4.5,55.4,92.9,97.5,...,179,1,Advanced,Medium,65.3,84.8,B,High,Practice Exercises,44.0
88,DS089,Neha Sharma,Female,20.0,4,55.0,1.8,70.8,96.7,41.6,...,38,4,Beginner,High,31.2,75.2,B,High,Practice Exercises,125.0
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.8,...,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects,34.5
91,DS092,Simran Verma,Female,20.0,7,60.9,1.2,95.6,77.0,86.8,...,26,5,Intermediate,Medium,26.9,78.7,B,High,Practice Exercises,94.0
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.9,...,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects,12.0
100,DS101,Saurabh Singh,Female,22.0,7,58.1,3.2,50.4,64.3,73.5,...,79,0,Intermediate,NaN,46.4,72.1,C,High,Video Tutorials and Quizzes,148.0
103,DS104,Priya Verma,Female,19.0,8,57.6,3.7,96.5,42.4,42.9,...,78,0,Intermediate,Low,50.2,70.6,C,High,Video Tutorials and Quizzes,159.0
104,DS105,Nisha Gupta,Female,19.0,5,55.2,5.8,80.2,92.1,64.6,...,181,5,Beginner,Low,74.7,86.8,A,High,Advanced Projects,29.5
109,DS110,Riya Sharma,Male,21.0,8,58.3,4.0,81.8,77.2,65.1,...,57,1,Intermediate,Low,51.1,78.2,B,High,Practice Exercises,99.5
115,DS116,Vivaan Kumar,Female,22.0,3,63.0,2.6,57.7,52.4,76.5,...,194,5,Beginner,Medium,52.1,66.6,C,High,Video Tutorials and Quizzes,184.0
124,DS125,Sneha Gupta,Male,19.0,7,56.2,1.7,98.0,73.0,97.8,...,87,3,Intermediate,Low,34.6,80.5,B,High,Practice Exercises,74.5
131,DS132,Priya Kumar,Male,22.0,7,56.7,4.7,81.2,88.1,41.8,...,67,5,Advanced,High,57.1,73.0,C,High,Video Tutorials and Quizzes,140.5
132,DS133,Aman Sharma,Male,21.0,5,62.8,1.5,81.3,85.9,52.2,...,90,0,Advanced,Medium,34.9,66.5,C,High,Video Tutorials and Quizzes,185.5
148,DS149,Rohan Chauhan,Male,22.0,4,61.5,4.6,55.5,60.3,55.1,...,198,0,Beginner,Medium,68.0,78.0,B,High,Practice Exercises,103.0
154,DS155,Aditya Sharma,Female,20.0,4,62.6,3.5,77.9,42.0,58.6,...,110,3,Intermediate,High,52.5,73.8,C,High,Video Tutorials and Quizzes,138.0
159,DS160,Aditya Verma,Female,19.0,3,64.7,2.8,48.8,85.8,61.5,...,154,0,Intermediate,Medium,50.9,75.7,B,High,Practice Exercises,118.0
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.7,...,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice,195.0
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.9,...,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice,198.0
165,DS166,Priya Sinha,Female,20.0,4,62.4,1.9,97.1,66.7,86.3,...,101,3,Beginner,High,38.9,81.2,B,High,Practice Exercises,67.5
172,DS173,Rahul Sharma,Female,23.0,4,55.5,3.1,61.2,69.2,72.5,...,58,0,Intermediate,Medium,43.3,67.1,C,High,Video Tutorials and Quizzes,182.0
173,DS174,Ananya Singh,Female,21.0,5,58.5,3.7,92.4,75.4,49.7,...,181,0,Intermediate,Medium,58.7,76.3,B,High,Practice Exercises,114.5
176,DS177,Kavya Yadav,Female,20.0,5,62.2,1.1,86.6,67.5,53.8,...,179,3,Intermediate,High,38.7,74.7,C,High,Video Tutorials and Quizzes,129.5
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects,14.5
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.5,...,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes,163.0
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5

In [36]:
# 20
df[df["predicted_score"] > 80][["student_name", "predicted_score"]]

      student_name  predicted_score
3     Aditya Kumar             80.1
6     Aarav Mishra             83.6
11    Rahul Mishra             81.2
12    Aditya Verma             82.2
14    Kunal Sharma             95.9
..             ...              ...
190   Riya Chauhan             83.6
191     Isha Sinha             87.6
196  Arjun Chauhan             86.8
198    Priya Gupta             92.6
199   Vivaan Singh             89.3

[81 rows x 2 columns]

In [35]:
# 21
df[(df["semester"] == 4) & (df["attendance_percent"] > 80)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises,81.0
27,DS028,Riya Chauhan,Male,22.0,4,85.7,2.7,59.3,69.8,80.0,...,129,3,Intermediate,High,53.3,75.3,B,Low,Practice Exercises,123.0
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,3.8,50.0,83.6,70.6,...,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises,96.5
42,DS043,Saurabh Pandey,Female,18.0,4,89.6,1.3,47.5,77.2,57.6,...,124,0,Intermediate,Medium,42.7,65.3,C,Low,Video Tutorials and Quizzes,190.0
67,DS068,Priya Pandey,Female,18.0,4,80.5,5.9,70.9,50.9,66.5,...,34,0,Beginner,High,70.0,81.6,B,Low,Practice Exercises,65.5
76,DS077,Simran Kumar,Male,22.0,4,94.4,3.1,70.4,99.4,35.0,...,105,2,Beginner,Low,56.8,74.6,C,Low,Video Tutorials and Quizzes,131.0
99,DS100,Vivaan Verma,Female,19.0,4,90.7,4.3,99.6,57.0,58.3,...,30,0,Beginner,Medium,59.5,81.8,B,Low,Practice Exercises,63.5
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects,33.0
118,DS119,Aditya Yadav,Female,23.0,4,99.7,4.3,75.7,83.8,65.2,...,45,4,Beginner,Medium,62.9,80.6,B,Low,Practice Exercises,72.0
123,DS124,Simran Verma,Male,19.0,4,92.0,1.7,92.4,95.4,66.7,...,134,3,Intermediate,Medium,47.3,85.0,A,Low,Advanced Projects,41.0
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.4,...,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes,153.0
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.7,...,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects,14.5
163,DS164,Arjun Verma,Male,21.0,4,85.1,4.0,94.1,51.1,40.1,...,167,3,Intermediate,High,66.6,73.0,C,Low,Video Tutorials and Quizzes,140.5
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.4,...,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises,54.0
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.9,...,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes,161.5

In [34]:
# 22
df[(df["previous_cgpa"] > 8.0) & (df["predicted_score"] > 75)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises,125.0
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises,81.0
6,DS007,Aarav Mishra,Female,23.0,7,87.8,4.2,93.8,68.3,42.8,...,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises,54.0
12,DS013,Aditya Verma,Female,21.0,5,64.9,4.6,89.5,60.9,41.3,...,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises,59.0
14,DS015,Kunal Sharma,Male,20.0,5,93.5,3.0,93.8,91.1,95.8,...,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,DS193,Saurabh Mishra,Male,22.0,7,94.4,1.9,60.3,47.8,78.9,...,93,2,Intermediate,High,46.2,78.0,B,Low,Practice Exercises,103.0
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises,114.5
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects,29.5
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects,16.0

In [33]:
# 23
df[df["semester"].isin([2, 4])]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises,81.0
13,DS014,Simran Mishra,Male,23.0,4,66.6,4.3,89.9,73.3,69.4,...,149,4,Advanced,Medium,63.0,79.9,B,Medium,Practice Exercises,83.5
20,DS021,Kavya Sharma,Female,21.0,4,59.2,3.9,47.0,67.9,70.3,...,95,0,Beginner,High,53.6,69.8,C,High,Video Tutorials and Quizzes,170.0
27,DS028,Riya Chauhan,Male,22.0,4,85.7,2.7,59.3,69.8,80.0,...,129,3,Intermediate,High,53.3,75.3,B,Low,Practice Exercises,123.0
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,2.8,59.3,67.2,37.1,...,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice,194.0
37,DS038,Isha Gupta,Female,18.0,4,58.7,5.4,75.3,49.9,61.7,...,186,2,Intermediate,Medium,72.8,80.5,B,High,Practice Exercises,74.5
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,3.8,50.0,83.6,70.6,...,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises,96.5
42,DS043,Saurabh Pandey,Female,18.0,4,89.6,1.3,47.5,77.2,57.6,...,124,0,Intermediate,Medium,42.7,65.3,C,Low,Video Tutorials and Quizzes,190.0
48,DS049,Rahul Verma,Male,19.0,4,66.0,3.5,63.2,96.0,35.5,...,121,3,Advanced,Low,54.2,70.5,C,Medium,Video Tutorials and Quizzes,161.5
67,DS068,Priya Pandey,Female,18.0,4,80.5,5.9,70.9,50.9,66.5,...,34,0,Beginner,High,70.0,81.6,B,Low,Practice Exercises,65.5
76,DS077,Simran Kumar,Male,22.0,4,94.4,3.1,70.4,99.4,35.0,...,105,2,Beginner,Low,56.8,74.6,C,Low,Video Tutorials and Quizzes,131.0
84,DS085,Sneha Sinha,Male,22.0,4,59.8,4.5,55.4,92.9,97.5,...,179,1,Advanced,Medium,65.3,84.8,B,High,Practice Exercises,44.0
86,DS087,Rahul Sharma,Female,23.0,4,74.5,5.2,66.6,50.8,84.0,...,77,2,Beginner,High,66.4,84.9,B,Medium,Practice Exercises,42.5
88,DS089,Neha Sharma,Female,20.0,4,55.0,1.8,70.8,96.7,41.6,...,38,4,Beginner,High,31.2,75.2,B,High,Practice Exercises,125.0
99,DS100,Vivaan Verma,Female,19.0,4,90.7,4.3,99.6,57.0,58.3,...,30,0,Beginner,Medium,59.5,81.8,B,Low,Practice Exercises,63.5
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects,33.0
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.0,...,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects,19.0
114,DS115,Saurabh Pandey,Female,18.0,4,66.5,2.5,85.3,91.1,78.6,...,192,1,Beginner,Medium,52.0,86.5,A,Medium,Advanced Projects,32.0
118,DS119,Aditya Yadav,Female,23.0,4,99.7,4.3,75.7,83.8,65.2,...,45,4,Beginner,Medium,62.9,80.6,B,Low,Practice Exercises,72.0
123,DS124,Simran Verma,Male,19.0,4,92.0,1.7,92.4,95.4,66.7,...,134,3,Intermediate,Medium,47.3,85.0,A,Low,Advanced Projects,41.0
130,DS131,Aarav Chauhan,Female,19.0,4,66.4,4.9,90.4,69.7,60.1,...,154,3,Intermediate,High,68.1,82.0,B,Medium,Practice Exercises,60.0
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.8,...,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises,69.0
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.4,...,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes,153.0
148,DS149,Rohan Chauhan,Male,22.0,4,61.5,4.6,55.5,60.3,55.1,...,198,0,Beginner,Medium,68.0,78.0,B,High,Practice Exercises,103.0
150,DS151,Pooja Sinha,Female,19.0,4,75.8,3.1,80.8,72.7,39.0,...,147,2,Beginner,High,55.5,74.1,C,Low,Video Tutorials and Quizzes,136.0
151,DS152,Aman Gupta,Female,21.0,4,69.9,4.8,73.6,52.3,92.1,...,164,4,Intermediate,High,69.0,87.4,A,Medium,Advanced Projects,24.0
154,DS155,Aditya Sharma,Female,20.0,4,62.6,3.5,77.9,42.0,58.6,...,110,3,Intermediate,High,52.5,73.8,C,High,Video Tutorials and Quizzes,138.0
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.7,...,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects,14.5
163,DS164,Arjun Verma,Male,21.0,4,85.1,4.0,94.1,51.1,40.1,...,167,3,Intermediate,High,66.6,73.0,C,Low,Video Tutorials and Quizzes,140.5
165,DS166,Priya Sinha,Female,20.0,4,62.4,1.9,97.1,66.7,86.3,...,101,3,Beginner,High,38.9,81.2,B,High,Practice Exercises,67.5
172,DS173,Rahul Sharma,Female,23.0,4,55.5,3.1,61.2,69.2,72.5,...,58,0,Intermediate,Medium,43.3,67.1,C,High,Video Tutorials and Quizzes,182.0
178,DS179,Isha Sharma,Male,19.0,4,66.7,2.0,48.2,60.5,52.6,...,138,3,Intermediate,High,43.7,70.2,C,Medium,Video Tutorials and Quizzes,165.5
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.4,...,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises,54.0
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects,23.0
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.9,...,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes,161.5

In [32]:
# 24
df[(df["gender"] == "Female") & (df["python_skill_level"] == "Advanced")]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
12,DS013,Aditya Verma,Female,21.0,5,64.9,4.6,89.5,60.9,41.3,...,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises,59.0
25,DS026,Nisha Chauhan,Female,19.0,5,77.6,5.3,81.2,49.8,39.6,...,137,2,Advanced,Medium,72.8,78.1,B,Low,Practice Exercises,101.0
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,2.8,59.3,67.2,37.1,...,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice,194.0
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,3.8,50.0,83.6,70.6,...,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises,96.5
66,DS067,Simran Singh,Female,18.0,7,70.4,2.3,65.9,75.4,52.4,...,146,1,Advanced,Medium,47.7,72.9,C,Medium,Video Tutorials and Quizzes,142.0
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.8,...,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises,103.0
111,DS112,Neha Sinha,Female,21.0,5,72.1,2.0,71.4,51.7,45.8,...,36,4,Advanced,Medium,36.9,67.7,C,Medium,Video Tutorials and Quizzes,179.0
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects,17.0
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects,5.0
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.8,...,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises,69.0
137,DS138,Isha Mishra,Female,22.0,8,94.3,4.2,86.9,49.6,65.0,...,14,2,Advanced,Low,58.3,74.7,C,Low,Video Tutorials and Quizzes,129.5
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.4,...,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes,153.0
143,DS144,Neha Yadav,Female,23.0,6,72.3,3.9,77.3,51.1,58.5,...,122,5,Advanced,Medium,59.0,72.5,C,Medium,Video Tutorials and Quizzes,144.5
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.7,...,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice,195.0
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5

In [31]:
# 25
df[df["study_hours_per_day"].between(2, 5)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5,78.7,48.4,54.0,...,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes,177.0
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises,81.0
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6,66.4,56.3,88.9,...,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes,151.5
6,DS007,Aarav Mishra,Female,23.0,7,87.8,4.2,93.8,68.3,42.8,...,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises,54.0
7,DS008,Sneha Sharma,Female,18.0,6,80.3,4.5,52.7,76.3,70.1,...,80,2,Intermediate,High,62.5,75.7,B,Low,Practice Exercises,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises,99.5
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects,29.5
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.9,...,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes,161.5
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects,16.0

In [30]:
# 26
df[df["grade"].isin(["A", "B"])]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises,125.0
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6,73.6,72.8,47.0,...,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises,81.0
6,DS007,Aarav Mishra,Female,23.0,7,87.8,4.2,93.8,68.3,42.8,...,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises,54.0
7,DS008,Sneha Sharma,Female,18.0,6,80.3,4.5,52.7,76.3,70.1,...,80,2,Intermediate,High,62.5,75.7,B,Low,Practice Exercises,118.0
11,DS012,Rahul Mishra,Female,21.0,5,71.6,2.2,89.2,68.2,98.9,...,153,0,Beginner,Medium,47.7,81.2,B,Medium,Practice Exercises,67.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises,99.5
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects,29.5
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects,16.0

In [29]:
# 27
df[df["risk_level"].isin(["Medium", "High"])]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8,48.2,92.0,74.1,...,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises,125.0
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5,78.7,48.4,54.0,...,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes,177.0
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6,66.4,56.3,88.9,...,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes,151.5
5,DS006,Aman Sinha,Male,18.0,6,68.2,1.1,55.9,82.7,86.4,...,50,3,Advanced,Medium,29.9,74.8,C,Medium,Video Tutorials and Quizzes,128.0
10,DS011,Nisha Mishra,Female,19.0,5,68.5,2.4,47.0,76.6,67.7,...,138,2,Intermediate,Medium,47.4,65.0,C,Medium,Video Tutorials and Quizzes,192.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects,14.5
187,DS188,Vivaan Chauhan,Female,22.0,6,93.9,3.0,61.1,49.1,52.3,...,48,0,Intermediate,Medium,51.3,64.5,D,Medium,Extra Mentoring and Practice,193.0
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.5,...,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes,163.0
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects,23.0
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises,88.5

In [28]:
# 28
df[df["mathematics_skill"].isin(["Good", "Excellent"])]

Empty DataFrame
Columns: [student_id, student_name, gender, age, semester, attendance_percent, study_hours_per_day, assignment_average, quiz_average, mid_sem_score, previous_cgpa, lab_hours_per_week, online_activity_count, projects_completed, python_skill_level, mathematics_skill, engagement_score, predicted_score, grade, risk_level, learning_recommendation, rank]
Index: []

[0 rows x 22 columns]

In [27]:
# 29
df[(df["projects_completed"] >= 2) & (df["engagement_score"] > 70)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
15,DS016,Kavya Singh,Female,19.0,8,75.2,6.0,54.7,41.1,67.1,...,145,2,Intermediate,Medium,78.4,72.2,C,Low,Video Tutorials and Quizzes,147.0
18,DS019,Aarav Sharma,Female,NaN,3,72.8,5.2,96.2,44.2,48.6,...,136,2,Beginner,Medium,70.7,80.9,B,Medium,Practice Exercises,70.0
21,DS022,Ananya Gupta,Female,18.0,7,67.2,5.8,70.1,90.5,47.6,...,177,3,Beginner,High,77.4,81.8,B,Medium,Practice Exercises,63.5
25,DS026,Nisha Chauhan,Female,19.0,5,77.6,5.3,81.2,49.8,39.6,...,137,2,Advanced,Medium,72.8,78.1,B,Low,Practice Exercises,101.0
32,DS033,Aryan Kumar,Male,23.0,6,65.7,5.5,77.6,61.0,81.0,...,176,2,Beginner,Medium,74.5,83.8,B,Medium,Practice Exercises,51.0
35,DS036,Neha Kumar,Female,22.0,8,81.3,5.5,47.5,56.9,96.8,...,165,4,Beginner,Low,77.5,88.0,A,Low,Advanced Projects,20.0
37,DS038,Isha Gupta,Female,18.0,4,58.7,5.4,75.3,49.9,61.7,...,186,2,Intermediate,Medium,72.8,80.5,B,High,Practice Exercises,74.5
61,DS062,Isha Yadav,Female,18.0,6,73.9,5.6,64.9,74.8,76.1,...,90,3,Intermediate,Medium,70.5,78.4,B,Medium,Practice Exercises,96.5
65,DS066,Kavya Pandey,Male,23.0,5,98.3,5.7,52.8,64.4,56.1,...,170,4,Beginner,Low,83.8,75.2,B,Low,Practice Exercises,125.0
83,DS084,Riya Singh,Male,22.0,8,81.7,5.1,64.1,80.7,71.8,...,156,3,Advanced,High,73.7,81.6,B,Low,Practice Exercises,65.5
104,DS105,Nisha Gupta,Female,19.0,5,55.2,5.8,80.2,92.1,64.6,...,181,5,Beginner,Low,74.7,86.8,A,High,Advanced Projects,29.5
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.8,...,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises,103.0
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects,17.0
156,DS157,Nisha Singh,Male,19.0,8,72.1,5.9,63.5,57.8,94.7,...,130,2,Advanced,Medium,75.6,80.3,B,Medium,Practice Exercises,78.0
158,DS159,Pooja Yadav,Male,18.0,7,91.3,5.2,59.0,41.9,83.1,...,165,5,Advanced,Medium,77.6,75.1,B,Low,Practice Exercises,127.0
175,DS176,Riya Kumar,Male,23.0,7,78.9,5.2,76.9,73.6,41.8,...,167,2,Intermediate,Low,74.7,75.7,B,Low,Practice Exercises,118.0
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.0,...,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects,7.0
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects,14.5
185,DS186,Neha Gupta,Male,22.0,7,92.0,5.0,93.6,82.0,41.8,...,137,3,Intermediate,Low,74.0,84.6,B,Low,Practice Exercises,46.0
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0

In [26]:
# 30
df[
    (df["attendance_percent"] > 85)
    & (df["study_hours_per_day"] > 3)
    & (df["grade"] == "A")
]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
17,DS018,Arjun Sharma,Male,18.0,3,99.8,3.3,60.4,93.0,83.6,...,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects,8.0
28,DS029,Saurabh Gupta,Female,18.0,5,99.6,3.1,65.5,86.6,57.2,...,122,4,Intermediate,Medium,59.5,85.9,A,Low,Advanced Projects,37.0
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.2,...,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects,38.5
55,DS056,Aman Sharma,Male,19.0,6,90.7,4.1,74.3,93.6,86.3,...,164,0,Beginner,Medium,68.6,85.4,A,Low,Advanced Projects,40.0
71,DS072,Arjun Verma,Female,20.0,5,92.9,5.2,97.5,49.3,75.5,...,49,0,Intermediate,Medium,68.7,87.1,A,Low,Advanced Projects,26.5
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects,1.0
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects,22.0
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects,33.0
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.0,...,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects,29.5
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects,16.0

In [25]:
# 31
df.sort_values(by="predicted_score", ascending=False)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects,1.0
14,DS015,Kunal Sharma,Male,20.0,5,93.5,3.0,93.8,91.1,95.8,...,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects,2.0
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.4,...,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects,3.0
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects,4.0
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,DS073,Saurabh Sinha,Female,20.0,5,58.5,1.0,98.2,40.3,41.7,...,58,4,Intermediate,Medium,27.3,61.2,D,High,Extra Mentoring and Practice,196.0
167,DS168,Sneha Kumar,Male,20.0,8,82.5,2.4,56.4,71.0,35.4,...,52,3,Beginner,Medium,44.0,61.1,D,Medium,Extra Mentoring and Practice,197.0
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.9,...,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice,198.0
145,DS146,Aman Singh,Male,20.0,3,90.1,1.0,48.2,53.5,43.5,...,45,4,Beginner,Low,34.1,60.3,D,Medium,Extra Mentoring and Practice,199.0
94,DS095,Aryan Singh,Female,21.0,3,78.3,1.4,64.3,42.0,40.1,...,112,1,Intermediate,High,39.7,60.0,D,Medium,Extra Mentoring and Practice,200.0

In [24]:
# 32
df.sort_values(by="predicted_score", ascending=False).head(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects,1.0
14,DS015,Kunal Sharma,Male,20.0,5,93.5,3.0,93.8,91.1,95.8,...,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects,2.0
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.4,...,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects,3.0
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects,4.0
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects,5.0
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects,6.0
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.0,...,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects,7.0
17,DS018,Arjun Sharma,Male,18.0,3,99.8,3.3,60.4,93.0,83.6,...,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects,8.0
119,DS120,Pooja Chauhan,Male,23.0,8,75.3,4.8,64.1,79.9,86.7,...,101,2,Beginner,High,65.3,91.1,A,Low,Advanced Projects,9.5
19,DS020,Aarav Sinha,Female,20.0,8,71.2,2.5,89.5,88.6,91.4,...,66,3,Intermediate,Medium,43.1,91.1,A,Medium,Advanced Projects,9.5

In [23]:
# 33
df.sort_values(by="predicted_score", ascending=True).head(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
94,DS095,Aryan Singh,Female,21.0,3,78.3,1.4,64.3,42.0,40.1,...,112,1,Intermediate,High,39.7,60.0,D,Medium,Extra Mentoring and Practice,200.0
145,DS146,Aman Singh,Male,20.0,3,90.1,1.0,48.2,53.5,43.5,...,45,4,Beginner,Low,34.1,60.3,D,Medium,Extra Mentoring and Practice,199.0
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.9,...,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice,198.0
167,DS168,Sneha Kumar,Male,20.0,8,82.5,2.4,56.4,71.0,35.4,...,52,3,Beginner,Medium,44.0,61.1,D,Medium,Extra Mentoring and Practice,197.0
72,DS073,Saurabh Sinha,Female,20.0,5,58.5,1.0,98.2,40.3,41.7,...,58,4,Intermediate,Medium,27.3,61.2,D,High,Extra Mentoring and Practice,196.0
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.7,...,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice,195.0
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,2.8,59.3,67.2,37.1,...,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice,194.0
187,DS188,Vivaan Chauhan,Female,22.0,6,93.9,3.0,61.1,49.1,52.3,...,48,0,Intermediate,Medium,51.3,64.5,D,Medium,Extra Mentoring and Practice,193.0
10,DS011,Nisha Mishra,Female,19.0,5,68.5,2.4,47.0,76.6,67.7,...,138,2,Intermediate,Medium,47.4,65.0,C,Medium,Video Tutorials and Quizzes,192.0
174,DS175,Arjun Kumar,Female,19.0,6,74.4,1.7,94.0,60.8,45.0,...,172,2,Intermediate,High,46.0,65.1,C,Medium,Video Tutorials and Quizzes,191.0

In [22]:
# 34
df.loc[df["predicted_score"].idxmax()]

student_id                             DS074
student_name                     Neha Pandey
gender                                  Male
age                                     20.0
semester                                   7
attendance_percent                      89.2
study_hours_per_day                      4.6
assignment_average                      80.0
quiz_average                            98.8
mid_sem_score                           93.7
previous_cgpa                            8.1
lab_hours_per_week                       5.5
online_activity_count                    118
projects_completed                         1
python_skill_level                  Beginner
mathematics_skill                     Medium
engagement_score                        68.5
predicted_score                         96.3
grade                                      A
risk_level                               Low
learning_recommendation    Advanced Projects
rank                                     1.0
Name: 73, dtype: object

In [21]:
# 35
df.loc[df["predicted_score"].idxmin()]

student_id                                        DS095
student_name                                Aryan Singh
gender                                           Female
age                                                21.0
semester                                              3
attendance_percent                                 78.3
study_hours_per_day                                 1.4
assignment_average                                 64.3
quiz_average                                       42.0
mid_sem_score                                      40.1
previous_cgpa                                      6.91
lab_hours_per_week                                  1.1
online_activity_count                               112
projects_completed                                    1
python_skill_level                         Intermediate
mathematics_skill                                  High
engagement_score                                   39.7
predicted_score                                    60.0
grade                                                 D
risk_level                                       Medium
learning_recommendation    Extra Mentoring and Practice
rank                                              200.0
Name: 94, dtype: object

In [20]:
# 36
df.sort_values(by="previous_cgpa", ascending=False)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
38,DS039,Riya Kumar,Female,19.0,3,73.7,2.4,NaN,91.9,87.8,...,190,4,Intermediate,High,52.8,84.7,B,Medium,Practice Exercises,45.0
142,DS143,Isha Verma,Female,23.0,3,74.5,1.4,57.1,75.9,82.8,...,54,0,Intermediate,Medium,34.1,79.9,B,Medium,Practice Exercises,83.5
139,DS140,Kavya Sinha,Male,19.0,7,71.6,2.6,53.2,58.3,92.0,...,134,3,Intermediate,High,49.4,80.5,B,Medium,Practice Exercises,74.5
93,DS094,Ananya Sinha,Female,18.0,6,90.1,1.2,71.4,46.3,50.7,...,89,5,Intermediate,Medium,39.2,72.7,C,Low,Video Tutorials and Quizzes,143.0
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.8,...,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects,34.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,DS003,Aditya Gupta,Female,20.0,7,75.3,1.1,96.8,73.8,60.1,...,101,3,Beginner,Medium,35.7,69.1,C,Low,Video Tutorials and Quizzes,175.0
61,DS062,Isha Yadav,Female,18.0,6,73.9,5.6,64.9,74.8,76.1,...,90,3,Intermediate,Medium,70.5,78.4,B,Medium,Practice Exercises,96.5
92,DS093,Pooja Sinha,Female,21.0,8,81.2,2.3,88.9,58.6,64.6,...,73,1,Intermediate,Medium,44.5,69.7,C,Low,Video Tutorials and Quizzes,171.0
167,DS168,Sneha Kumar,Male,20.0,8,82.5,2.4,56.4,71.0,35.4,...,52,3,Beginner,Medium,44.0,61.1,D,Medium,Extra Mentoring and Practice,197.0
137,DS138,Isha Mishra,Female,22.0,8,94.3,4.2,86.9,49.6,65.0,...,14,2,Advanced,Low,58.3,74.7,C,Low,Video Tutorials and Quizzes,129.5

In [19]:
# 37
df.sort_values(by=["semester", "predicted_score"], ascending=[True, False])

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,rank
17,DS018,Arjun Sharma,Male,18.0,3,99.8,3.3,60.4,93.0,83.6,...,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects,8.0
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects,17.0
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.6,...,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects,29.5
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects,29.5
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.5,...,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects,38.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,DS093,Pooja Sinha,Female,21.0,8,81.2,2.3,88.9,58.6,64.6,...,73,1,Intermediate,Medium,44.5,69.7,C,Low,Video Tutorials and Quizzes,171.0
85,DS086,Simran Verma,Male,19.0,8,89.0,2.3,55.6,45.0,56.2,...,107,3,Beginner,High,49.2,67.9,C,Low,Video Tutorials and Quizzes,178.0
75,DS076,Saurabh Mishra,Male,18.0,8,81.8,2.2,51.6,44.6,80.3,...,117,0,Intermediate,Medium,47.4,67.3,C,Low,Video Tutorials and Quizzes,180.5
167,DS168,Sneha Kumar,Male,20.0,8,82.5,2.4,56.4,71.0,35.4,...,52,3,Beginner,Medium,44.0,61.1,D,Medium,Extra Mentoring and Practice,197.0
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.9,...,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice,198.0

In [18]:
# 38
df["rank"] = df["predicted_score"].rank(ascending=False)

In [17]:
# 39
df.sort_values(by="engagement_score", ascending=False).head(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
65,DS066,Kavya Pandey,Male,23.0,5,98.3,5.7,52.8,64.4,56.1,...,5.1,170,4,Beginner,Low,83.8,75.2,B,Low,Practice Exercises
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.8,...,5.2,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.0,...,6.4,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects
15,DS016,Kavya Singh,Female,19.0,8,75.2,6.0,54.7,41.1,67.1,...,2.9,145,2,Intermediate,Medium,78.4,72.2,C,Low,Video Tutorials and Quizzes
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.9,...,6.1,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects
158,DS159,Pooja Yadav,Male,18.0,7,91.3,5.2,59.0,41.9,83.1,...,2.5,165,5,Advanced,Medium,77.6,75.1,B,Low,Practice Exercises
35,DS036,Neha Kumar,Female,22.0,8,81.3,5.5,47.5,56.9,96.8,...,3.6,165,4,Beginner,Low,77.5,88.0,A,Low,Advanced Projects
21,DS022,Ananya Gupta,Female,18.0,7,67.2,5.8,70.1,90.5,47.6,...,5.6,177,3,Beginner,High,77.4,81.8,B,Medium,Practice Exercises
16,DS017,Isha Yadav,Female,23.0,8,81.5,5.9,71.8,94.4,63.2,...,5.2,120,0,Beginner,Medium,77.2,87.1,A,Low,Advanced Projects

In [16]:
# 40
df.loc[df["online_activity_count"].idxmax()]

student_id                                       DS034
student_name                              Aditya Singh
gender                                          Female
age                                               21.0
semester                                             8
attendance_percent                                57.5
study_hours_per_day                                1.6
assignment_average                                51.5
quiz_average                                      79.0
mid_sem_score                                     83.5
previous_cgpa                                      7.8
lab_hours_per_week                                 7.7
online_activity_count                              200
projects_completed                                   3
python_skill_level                            Beginner
mathematics_skill                                 High
engagement_score                                  43.2
predicted_score                                   72.4
grade                                                C
risk_level                                        High
learning_recommendation    Video Tutorials and Quizzes
Name: 33, dtype: object

In [15]:
# 41
df.groupby("semester")["predicted_score"].mean()

semester
3    77.084615
4    78.380000
5    79.244737
6    77.290909
7    77.473529
8    77.491176
Name: predicted_score, dtype: float64

In [14]:
# 42
df.groupby("semester")["attendance_percent"].mean()

semester
3    79.284615
4    75.508571
5    73.623684
6    79.024242
7    78.608824
8    79.679412
Name: attendance_percent, dtype: float64

In [13]:
# 43
df.groupby("gender")["study_hours_per_day"].mean()

gender
Female    3.373333
Male      3.489474
Name: study_hours_per_day, dtype: float64

In [12]:
# 44
df["grade"].value_counts()

grade
B    86
C    65
A    41
D     8
Name: count, dtype: int64

In [11]:
# 45
df["risk_level"].value_counts()

risk_level
Low       111
Medium     52
High       37
Name: count, dtype: int64

In [10]:
# 46
df.groupby("python_skill_level")["predicted_score"].mean()

python_skill_level
Advanced        78.751220
Beginner        77.455385
Intermediate    77.817021
Name: predicted_score, dtype: float64

In [9]:
# 47
df.groupby("mathematics_skill")["previous_cgpa"].mean()

mathematics_skill
High      7.539020
Low       7.218974
Medium    7.321089
Name: previous_cgpa, dtype: float64

In [8]:
# 48
df.groupby("semester")["engagement_score"].mean()

semester
3    54.403846
4    57.934286
5    55.778947
6    56.184848
7    53.920588
8    54.091176
Name: engagement_score, dtype: float64

In [7]:
# 49
df.groupby("grade")["predicted_score"].agg(["max", "min"])

        max   min
grade
A      96.3  85.0
B      84.9  75.1
C      74.8  65.0
D      64.5  60.0

In [6]:
# 50
df.groupby("semester").agg(
    avg_attendance=("attendance_percent", "mean"),
    avg_study_hours=("study_hours_per_day", "mean"),
    avg_predicted_score=("predicted_score", "mean"),
    student_count=("student_name", "count"),
)

          avg_attendance  avg_study_hours  avg_predicted_score  student_count
semester
3              79.284615         3.173077            77.084615             26
4              75.508571         3.617143            78.380000             35
5              73.623684         3.615789            79.244737             38
6              79.024242         3.654545            77.290909             33
7              78.608824         3.232353            77.473529             34
8              79.679412         3.197059            77.491176             34