In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('/diabetes.csv')

In [5]:
df.columns

Index(['id', 'chol', 'stab.glu', 'hdl', 'ratio', 'glyhb', 'location', 'age',
       'gender', 'height', 'weight', 'frame', 'bp.1s', 'bp.1d', 'bp.2s',
       'bp.2d', 'waist', 'hip', 'time.ppn'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        403 non-null    int64
 1   chol      402 non-null    float64
 2   stab.glu  403 non-null    int64
 3   hdl       402 non-null    float64
 4   ratio     402 non-null    float64
 5   glyhb     390 non-null    float64
 6   location  403 non-null    object
 7   age       403 non-null    int64
 8   gender    403 non-null    object
 9   height    398 non-null    float64
 10  weight    402 non-null    float64
 11  frame     391 non-null    object
 12  bp.1s     398 non-null    float64
 13  bp.1d     398 non-null    float64
 14  bp.2s     141 non-null    float64
 15  bp.2d     141 non-null    float64
 16  waist     401 non-null    float64
 17  hip       401 non-null    float64
 18  time.ppn  400 non-null    float64
dtypes: float64(13), int64(3), object(3)
memory usage: 59.9+ KB

In [8]:
df.dtypes

id            int64
chol        float64
stab.glu      int64
hdl         float64
ratio       float64
glyhb       float64
location     object
age           int64
gender       object
height      float64
weight      float64
frame        object
bp.1s       float64
bp.1d       float64
bp.2s       float64
bp.2d       float64
waist       float64
hip         float64
time.ppn    float64
dtype: object

In [9]:
df.head(10)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0
5,1008,248.0,94,69.0,3.6,4.81,Buckingham,34,male,71.0,190.0,large,132.0,86.0,NaN,NaN,36.0,42.0,195.0
6,1011,195.0,92,41.0,4.8,4.84,Buckingham,30,male,69.0,191.0,medium,161.0,112.0,161.0,112.0,46.0,49.0,720.0
7,1015,227.0,75,44.0,5.2,3.94,Buckingham,37,male,59.0,170.0,medium,NaN,NaN,NaN,NaN,34.0,39.0,1020.0
8,1016,177.0,87,49.0,3.6,4.84,Buckingham,45,male,69.0,166.0,large,160.0,80.0,128.0,86.0,34.0,40.0,300.0
9,1022,263.0,89,40.0,6.6,5.78,Buckingham,55,female,63.0,202.0,small,108.0,72.0,NaN,NaN,45.0,50.0,240.0

In [10]:
df.tail(10)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
393,41253,192.0,85,69.0,2.8,4.380000,Louisa,51,male,65.0,146.0,large,130.0,110.0,170.0,118.0,NaN,NaN,60.0
394,41254,169.0,104,58.0,2.9,4.820000,Louisa,25,female,60.0,154.0,medium,140.0,95.0,130.0,94.0,40.0,42.0,60.0
395,41500,179.0,85,50.0,3.6,4.990000,Louisa,37,male,66.0,136.0,medium,190.0,94.0,172.0,100.0,33.0,39.0,480.0
396,41501,216.0,84,64.0,3.4,NaN,Louisa,54,female,66.0,168.0,medium,132.0,90.0,126.0,80.0,38.0,42.0,330.0
397,41503,301.0,90,118.0,2.6,4.280000,Louisa,89,female,61.0,115.0,medium,218.0,90.0,238.0,90.0,31.0,41.0,210.0
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,130.0,94.0,35.0,39.0,210.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,146.0,102.0,32.0,43.0,180.0
400,41510,194.0,269,38.0,5.1,13.630000,Louisa,29,female,69.0,167.0,small,120.0,70.0,NaN,NaN,33.0,40.0,20.0
401,41752,199.0,76,52.0,3.8,4.490000,Louisa,41,female,63.0,197.0,medium,120.0,78.0,NaN,NaN,41.0,48.0,255.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,NaN,NaN,49.0,58.0,900.0

In [11]:
df.describe()

,id,chol,stab.glu,hdl,ratio,glyhb,age,height,weight,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
count,403.000000,402.000000,403.000000,402.000000,402.000000,390.000000,403.000000,398.000000,402.000000,398.000000,398.000000,141.000000,141.000000,401.000000,401.000000,400.000000
mean,15978.310174,207.845771,106.672457,50.445274,4.521642,5.589769,46.851117,66.020101,177.592040,136.904523,83.321608,152.382979,92.524823,37.900249,43.039900,341.250000
std,11881.122124,44.445557,53.076655,17.262626,1.727886,2.242595,16.312333,3.918515,40.340666,22.741033,13.589227,21.712952,11.555198,5.729313,5.656713,309.540953
min,1000.000000,78.000000,48.000000,12.000000,1.500000,2.680000,19.000000,52.000000,99.000000,90.000000,48.000000,110.000000,60.000000,26.000000,30.000000,5.000000
25%,4792.500000,179.000000,81.000000,38.000000,3.200000,4.380000,34.000000,63.000000,151.000000,121.250000,75.000000,138.000000,84.000000,33.000000,39.000000,90.000000
50%,15766.000000,204.000000,89.000000,46.000000,4.200000,4.840000,45.000000,66.000000,172.500000,136.000000,82.000000,149.000000,92.000000,37.000000,42.000000,240.000000
75%,20336.000000,230.000000,106.000000,59.000000,5.400000,5.600000,60.000000,69.000000,200.000000,146.750000,90.000000,161.000000,100.000000,41.000000,46.000000,517.500000
max,41756.000000,443.000000,385.000000,120.000000,19.299999,16.110001,92.000000,76.000000,325.000000,250.000000,124.000000,238.000000,124.000000,56.000000,64.000000,1560.000000

In [15]:
#check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [16]:
df.nunique()

id          403
chol        154
stab.glu    116
hdl          77
ratio        69
glyhb       239
location      2
age          68
gender        2
height       22
weight      140
frame         3
bp.1s        71
bp.1d        57
bp.2s        48
bp.2d        36
waist        30
hip          32
time.ppn     60
dtype: int64

In [17]:
df['weight']

0      121.0
1      218.0
2      256.0
3      119.0
4      183.0
       ...
398    173.0
399    154.0
400    167.0
401    197.0
402    220.0
Name: weight, Length: 403, dtype: float64

In [21]:
df['weight'].unique()

array([121., 218., 256., 119., 183., 190., 191., 170., 166., 202., 156.,
       195., 165., 157., 159., 126., 196., 178., 230., 288., 185., 113.,
       118., 252., 100., 145., 189., 174., 139., 186., 205., 214., 160.,
       192., 253., 137., 233., 180., 219., 154., 181., 187., 167., 220.,
       274., 217., 161., 235., 125., 102., 127., 245., 264., 142., 143.,
       173., 223., 169., 200., 215., 151., 110., 198., 197., 203., 150.,
       204., 212., 227., 175., 158., 263., 120., 172., 164., 244., 225.,
       140., 325., 266., 177., 146., 105., 277., 320., 163., 232., 210.,
       255., 308.,  nan, 123., 282., 171., 138., 179., 199., 147., 184.,
       130., 134., 251., 114., 209., 109., 144., 201., 136., 124., 153.,
       188., 259., 162., 141., 135., 155., 211., 115., 290., 168., 260.,
       250., 182., 176., 128.,  99., 270., 285., 216., 239., 248., 152.,
       237., 148., 257., 228., 289., 129., 262., 222., 224.])

In [19]:
#select Multiple columns
df[['age','gender','height']]

     age  gender  height
0     46  female    62.0
1     29  female    64.0
2     58  female    61.0
3     67    male    67.0
4     64    male    68.0
..   ...     ...     ...
398   53    male    69.0
399   51  female    63.0
400   29  female    69.0
401   41  female    63.0
402   68  female    64.0

[403 rows x 3 columns]

In [22]:
# No. of unique values of weight column
df['weight'].nunique()

140

In [23]:
# Filtering rows by condition
df[df['age']>50]

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
2,1002,228.0,92,37.0,6.2,4.640000,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.630000,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.720000,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0
9,1022,263.0,89,40.0,6.6,5.780000,Buckingham,55,female,63.0,202.0,small,108.0,72.0,NaN,NaN,45.0,50.0,240.0
10,1024,242.0,82,54.0,4.5,4.770000,Louisa,60,female,65.0,156.0,medium,130.0,90.0,130.0,90.0,39.0,45.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,41501,216.0,84,64.0,3.4,NaN,Louisa,54,female,66.0,168.0,medium,132.0,90.0,126.0,80.0,38.0,42.0,330.0
397,41503,301.0,90,118.0,2.6,4.280000,Louisa,89,female,61.0,115.0,medium,218.0,90.0,238.0,90.0,31.0,41.0,210.0
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,130.0,94.0,35.0,39.0,210.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,146.0,102.0,32.0,43.0,180.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,NaN,NaN,49.0,58.0,900.0

In [24]:
df.shape

(403, 19)

In [27]:
df[(df['age']>50) & (df['gender']=='female') ]

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
9,1022,263.0,89,40.0,6.6,5.78,Buckingham,55,female,63.0,202.0,small,108.0,72.0,NaN,NaN,45.0,50.0,240.0
10,1024,242.0,82,54.0,4.5,4.77,Louisa,60,female,65.0,156.0,medium,130.0,90.0,130.0,90.0,39.0,45.0,300.0
19,1250,196.0,206,41.0,4.8,11.24,Buckingham,62,female,65.0,196.0,large,178.0,90.0,NaN,NaN,46.0,51.0,540.0
23,1256,281.0,92,41.0,6.9,5.56,Buckingham,66,female,62.0,185.0,large,158.0,88.0,160.0,88.0,48.0,44.0,285.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,41075,221.0,126,48.0,4.6,5.53,Louisa,59,female,62.0,177.0,medium,130.0,78.0,NaN,NaN,39.0,45.0,60.0
396,41501,216.0,84,64.0,3.4,NaN,Louisa,54,female,66.0,168.0,medium,132.0,90.0,126.0,80.0,38.0,42.0,330.0
397,41503,301.0,90,118.0,2.6,4.28,Louisa,89,female,61.0,115.0,medium,218.0,90.0,238.0,90.0,31.0,41.0,210.0
399,41507,284.0,89,54.0,5.3,4.39,Louisa,51,female,63.0,154.0,medium,140.0,100.0,146.0,102.0,32.0,43.0,180.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,NaN,NaN,49.0,58.0,900.0

In [28]:
# Access rows by index
df.iloc[0:10]

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0
5,1008,248.0,94,69.0,3.6,4.81,Buckingham,34,male,71.0,190.0,large,132.0,86.0,NaN,NaN,36.0,42.0,195.0
6,1011,195.0,92,41.0,4.8,4.84,Buckingham,30,male,69.0,191.0,medium,161.0,112.0,161.0,112.0,46.0,49.0,720.0
7,1015,227.0,75,44.0,5.2,3.94,Buckingham,37,male,59.0,170.0,medium,NaN,NaN,NaN,NaN,34.0,39.0,1020.0
8,1016,177.0,87,49.0,3.6,4.84,Buckingham,45,male,69.0,166.0,large,160.0,80.0,128.0,86.0,34.0,40.0,300.0
9,1022,263.0,89,40.0,6.6,5.78,Buckingham,55,female,63.0,202.0,small,108.0,72.0,NaN,NaN,45.0,50.0,240.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [29]:
#Sort by columns
df.sort_values(by='age',ascending=True).head()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
114,4823,193.0,77,49.0,3.9,4.31,Louisa,19,female,61.0,119.0,small,118.0,70.0,NaN,NaN,32.0,38.0,300.0
250,17790,146.0,79,41.0,3.6,4.76,Buckingham,19,female,60.0,135.0,medium,108.0,58.0,NaN,NaN,33.0,40.0,240.0
17,1041,230.0,112,64.0,3.6,4.53,Louisa,20,male,67.0,159.0,medium,100.0,90.0,NaN,NaN,31.0,39.0,1440.0
373,40804,179.0,105,60.0,3.0,4.68,Louisa,20,female,58.0,170.0,medium,140.0,100.0,138.0,82.0,34.0,46.0,270.0
55,2763,193.0,106,63.0,3.1,6.35,Buckingham,20,female,68.0,274.0,small,165.0,110.0,153.0,100.0,49.0,58.0,60.0

In [30]:
df.sort_values(by='age',ascending=True).tail()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
107,4803,227.0,105,44.0,5.2,5.71,Louisa,83,female,59.0,125.0,medium,150.0,90.0,156.0,88.0,35.0,40.0,300.0
364,40784,226.0,279,52.0,4.3,10.07,Louisa,84,female,60.0,192.0,small,144.0,88.0,146.0,82.0,41.0,48.0,210.0
397,41503,301.0,90,118.0,2.6,4.28,Louisa,89,female,61.0,115.0,medium,218.0,90.0,238.0,90.0,31.0,41.0,210.0
69,2794,232.0,184,114.0,2.0,8.40,Buckingham,91,female,61.0,127.0,NaN,170.0,82.0,NaN,NaN,35.0,38.0,120.0
57,2770,165.0,94,69.0,2.4,4.98,Buckingham,92,female,62.0,217.0,large,160.0,82.0,NaN,NaN,51.0,51.0,180.0

In [32]:
# DEscending order
df.sort_values(by='age',ascending=False).head()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
57,2770,165.0,94,69.0,2.4,4.98,Buckingham,92,female,62.0,217.0,large,160.0,82.0,NaN,NaN,51.0,51.0,180.0
69,2794,232.0,184,114.0,2.0,8.40,Buckingham,91,female,61.0,127.0,NaN,170.0,82.0,NaN,NaN,35.0,38.0,120.0
397,41503,301.0,90,118.0,2.6,4.28,Louisa,89,female,61.0,115.0,medium,218.0,90.0,238.0,90.0,31.0,41.0,210.0
364,40784,226.0,279,52.0,4.3,10.07,Louisa,84,female,60.0,192.0,small,144.0,88.0,146.0,82.0,41.0,48.0,210.0
107,4803,227.0,105,44.0,5.2,5.71,Louisa,83,female,59.0,125.0,medium,150.0,90.0,156.0,88.0,35.0,40.0,300.0

In [33]:
# count values
df['age'].value_counts()

age
40    16
41    13
36    13
43    13
37    11
      ..
91     1
69     1
81     1
84     1
89     1
Name: count, Length: 68, dtype: int64

In [35]:
# group by and aggregate
df.groupby('age').mean(10)

,id,chol,stab.glu,hdl,ratio,glyhb,height,weight,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
age,,,,,,,,,,,,,,,
19,11306.500000,169.500000,78.000000,45.000000,3.750000,4.535000,60.500000,127.000000,113.000000,64.000000,NaN,NaN,32.500000,39.000000,270.000000
20,17641.300000,186.600000,90.800000,67.100000,2.910000,4.600000,66.200000,165.300000,121.200000,83.800000,145.5,91.0,35.100000,42.000000,582.000000
21,15341.500000,182.333333,86.500000,60.166667,3.166667,4.378333,65.333333,167.833333,121.833333,76.833333,117.0,68.0,35.166667,42.500000,281.666667
22,10050.200000,182.600000,76.600000,55.600000,3.460000,4.046000,65.200000,156.400000,109.400000,71.200000,NaN,NaN,34.400000,39.600000,450.000000
23,13878.714286,187.000000,83.285714,42.571429,4.500000,4.634286,68.428571,209.857143,123.857143,80.142857,150.0,85.0,41.428571,45.571429,481.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,4803.000000,227.000000,105.000000,44.000000,5.200000,5.710000,59.000000,125.000000,150.000000,90.000000,156.0,88.0,35.000000,40.000000,300.000000
84,40784.000000,226.000000,279.000000,52.000000,4.300000,10.070000,60.000000,192.000000,144.000000,88.000000,146.0,82.0,41.000000,48.000000,210.000000
89,41503.000000,301.000000,90.000000,118.000000,2.600000,4.280000,61.000000,115.000000,218.000000,90.000000,238.0,90.0,31.000000,41.000000,210.000000
91,2794.000000,232.000000,184.000000,114.000000,2.000000,8.400000,61.000000,127.000000,170.000000,82.000000,NaN,NaN,35.000000,38.000000,120.000000
92,2770.000000,165.000000,94.000000,69.000000,2.400000,4.980000,62.000000,217.000000,160.000000,82.000000,NaN,NaN,51.000000,51.000000,180.000000

In [36]:
df.groupby('age').mean(numeric_only=True)

,id,chol,stab.glu,hdl,ratio,glyhb,height,weight,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
age,,,,,,,,,,,,,,,
19,11306.500000,169.500000,78.000000,45.000000,3.750000,4.535000,60.500000,127.000000,113.000000,64.000000,NaN,NaN,32.500000,39.000000,270.000000
20,17641.300000,186.600000,90.800000,67.100000,2.910000,4.600000,66.200000,165.300000,121.200000,83.800000,145.5,91.0,35.100000,42.000000,582.000000
21,15341.500000,182.333333,86.500000,60.166667,3.166667,4.378333,65.333333,167.833333,121.833333,76.833333,117.0,68.0,35.166667,42.500000,281.666667
22,10050.200000,182.600000,76.600000,55.600000,3.460000,4.046000,65.200000,156.400000,109.400000,71.200000,NaN,NaN,34.400000,39.600000,450.000000
23,13878.714286,187.000000,83.285714,42.571429,4.500000,4.634286,68.428571,209.857143,123.857143,80.142857,150.0,85.0,41.428571,45.571429,481.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,4803.000000,227.000000,105.000000,44.000000,5.200000,5.710000,59.000000,125.000000,150.000000,90.000000,156.0,88.0,35.000000,40.000000,300.000000
84,40784.000000,226.000000,279.000000,52.000000,4.300000,10.070000,60.000000,192.000000,144.000000,88.000000,146.0,82.0,41.000000,48.000000,210.000000
89,41503.000000,301.000000,90.000000,118.000000,2.600000,4.280000,61.000000,115.000000,218.000000,90.000000,238.0,90.0,31.000000,41.000000,210.000000
91,2794.000000,232.000000,184.000000,114.000000,2.000000,8.400000,61.000000,127.000000,170.000000,82.000000,NaN,NaN,35.000000,38.000000,120.000000
92,2770.000000,165.000000,94.000000,69.000000,2.400000,4.980000,62.000000,217.000000,160.000000,82.000000,NaN,NaN,51.000000,51.000000,180.000000